// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyoLrkjP_EVlmF5pzNXOcCCZvDnOdRMqg',
    appId: '1:158132567808:web:5518205edad0060c3ebde5',
    messagingSenderId: '158132567808',
    projectId: 'todolist-409ad',
    authDomain: 'todolist-409ad.firebaseapp.com',
    storageBucket: 'todolist-409ad.firebasestorage.app',
    measurementId: 'G-BWJ00LEVTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChbGu6VW6zjH0xCuynopnpHFn7H6G515o',
    appId: '1:158132567808:android:0131e88798dfc02d3ebde5',
    messagingSenderId: '158132567808',
    projectId: 'todolist-409ad',
    storageBucket: 'todolist-409ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ3HW7ljcfA7GZGqET0O-TguvL015t3h4',
    appId: '1:158132567808:ios:02d8404cbdde80363ebde5',
    messagingSenderId: '158132567808',
    projectId: 'todolist-409ad',
    storageBucket: 'todolist-409ad.firebasestorage.app',
    androidClientId: '158132567808-hvdjabvmnh712blatlc4jjjmg02ek3bn.apps.googleusercontent.com',
    iosClientId: '158132567808-ivmgvuv7blih5kvlbq7mneqanvkumrj4.apps.googleusercontent.com',
    iosBundleId: 'com.todoapp.todoAppOfflineSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ3HW7ljcfA7GZGqET0O-TguvL015t3h4',
    appId: '1:158132567808:ios:02d8404cbdde80363ebde5',
    messagingSenderId: '158132567808',
    projectId: 'todolist-409ad',
    storageBucket: 'todolist-409ad.firebasestorage.app',
    androidClientId: '158132567808-hvdjabvmnh712blatlc4jjjmg02ek3bn.apps.googleusercontent.com',
    iosClientId: '158132567808-ivmgvuv7blih5kvlbq7mneqanvkumrj4.apps.googleusercontent.com',
    iosBundleId: 'com.todoapp.todoAppOfflineSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyoLrkjP_EVlmF5pzNXOcCCZvDnOdRMqg',
    appId: '1:158132567808:web:3f8cb13f21ad06ff3ebde5',
    messagingSenderId: '158132567808',
    projectId: 'todolist-409ad',
    authDomain: 'todolist-409ad.firebaseapp.com',
    storageBucket: 'todolist-409ad.firebasestorage.app',
    measurementId: 'G-JXYYEXYNMV',
  );
}
